name: Test

on:
  - pull_request
  - push

jobs:
  test-jekyll-geolexica:
    name: Geolexica server on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ "2.7", "3.0" ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rspec
